font_family      CommitMono
bold_font        CommitMono Bold
italic_font      CommitMono
bold_italic_font CommitMono Bold
font_size 11
text_composition_strategy legacy
window_padding_width 2
cursor_trail 3
background_blur 1
background_opacity 0.9

mouse_hide_wait 0
mouse_map left click ungrabbed no_op
mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt
map ctrl+shift+w no_op

# Tab bar as a pwd status bar
tab_bar_edge bottom
tab_bar_style separator
tab_bar_min_tabs 1
tab_separator " | "
tab_title_template " {index}: {tab.active_wd} "
