[[profile]]
name = "laptop"
    [[profile.output]]
    search  = ["v=California Institute of Technology", "m=0x1603"]
    enable = true

[[profile]]
name = "laptop_framework16"
    [[profile.output]]
    search  = ["m=0x0BC9", "s=", "v=BOE"]
    enable = true

[[profile]]
name = "home_office"
    [[profile.output]]
    search = ["s=CGS4KK3", "m=DELL S3422DWG"]
    enable = true

    [[profile.output]]
    search  = ["v=California Institute of Technology", "m=0x1603"]
    enable = false

[[profile]]
name = "home_office_framework16"
    [[profile.output]]
    search = ["s=CGS4KK3", "m=DELL S3422DWG"]
    enable = true

    [[profile.output]]
    search  = ["m=0x0BC9", "s=", "v=BOE"]
    enable = false
